name=dv_led_blink
version=0.0.1
author=David Vandensteen
maintainer=David Vandensteen <dvandensteen@gmail.com>
sentence=Simple library to blink an LED on Arduino boards in a non-blocking way.
paragraph=This library allows you to blink an LED connected to a digital pin on Arduino-compatible boards in a non-blocking way. It also supports specifying a custom interval, a number of blink cycles, or infinite blinking.
category=Device Control
url=https://github.com/David-Vandensteen/dv-led-blink
architectures=*
includes=dv_led_blink.h