name=dv_led_blink
version=1.1.0
author=David Vandensteen
maintainer=David Vandensteen <dvandensteen@gmail.com>
sentence=Non-blocking blink LED.
paragraph=With customizable interval and cycles.
category=Device Control
url=https://github.com/David-Vandensteen/dv-led-blink
architectures=*
includes=dv_led_blink.h